import SwiftUI
import AppKit

let brand = Color(red: 0.36, green: 0.30, blue: 0.92)

/// The running app's version (from the bundle's CFBundleShortVersionString).
let appVersion: String = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "dev"

/// Notes generated by an app version older than this are flagged for
/// re-generation, because this version changed the summary structure/quality.
/// Bump this whenever a release meaningfully changes generated-note output.
/// Bumped through 0.20.1: VAD (0.13), paragraphs (0.14), timeline (0.15),
/// Obsidian embeds + tags (0.17), and the big summary fixes - full-context
/// summaries (0.20.0) and reliable section/format + language (0.20.1) - all
/// changed note output, so anything older is worth re-generating.
let noteQualityBaseline = "0.20.1"

/// Compare two dotted versions ("0.3.2"). Returns -1, 0, or 1.
func semverCompare(_ a: String, _ b: String) -> Int {
	let pa = a.split(separator: ".").map { Int($0) ?? 0 }
	let pb = b.split(separator: ".").map { Int($0) ?? 0 }
	for i in 0..<max(pa.count, pb.count) {
		let x = i < pa.count ? pa[i] : 0
		let y = i < pb.count ? pb[i] : 0
		if x != y { return x < y ? -1 : 1 }
	}
	return 0
}

/// A note is "outdated" when it has no recorded version (pre-versioning) or its
/// version predates the quality baseline.
func noteIsOutdated(_ noteVersion: String?) -> Bool {
	guard let v = noteVersion, !v.isEmpty, v != "dev" else { return true }
	return semverCompare(v, noteQualityBaseline) < 0
}

/// Languages offered in the record-panel picker.
let meetingLanguages: [(code: String, name: String)] = [
	("auto", "Auto-detect"),
	("en", "English"),
	("uk", "Ukrainian"),
]

func durationLabel(_ seconds: Int) -> String {
	let h = seconds / 3600, m = (seconds % 3600) / 60, s = seconds % 60
	var parts: [String] = []
	if h > 0 { parts.append("\(h) hr") }
	if m > 0 { parts.append("\(m) min") }
	if s > 0 || parts.isEmpty { parts.append("\(s) sec") }
	return parts.joined(separator: " ")
}

struct ContentView: View {
	@EnvironmentObject var settings: AppSettings
	@EnvironmentObject var store: MeetingStore
	@EnvironmentObject var controller: RecordingController
	@EnvironmentObject var updates: UpdateChecker
	@State private var selection: Meeting.ID?
	@State private var query = ""

	private var filteredMeetings: [Meeting] {
		let q = query.trimmingCharacters(in: .whitespaces).lowercased()
		guard !q.isEmpty else { return store.meetings }
		return store.meetings.filter { $0.searchHay.contains(q) }
	}

	var body: some View {
		NavigationSplitView {
			VStack(spacing: 0) {
				List(filteredMeetings, selection: $selection) { meeting in
					MeetingRow(meeting: meeting)
						.contextMenu {
							Button("Delete", role: .destructive) {
								store.delete(meeting)
								if selection == meeting.id { selection = nil }
							}
						}
				}
				.listStyle(.sidebar)
				.searchable(text: $query, placement: .sidebar, prompt: "Search title or content")

				Divider()
				RecordPanel().environmentObject(controller).padding(14)
			}
			.navigationSplitViewColumnWidth(min: 250, ideal: 290)
		} detail: {
			if let id = selection, let meeting = store.meetings.first(where: { $0.id == id }) {
				// Only show processing state on the meeting actually being processed,
				// not whichever one happens to be selected.
				let isProcessingThis = controller.busy && controller.activeID == meeting.id
				MeetingDetail(
					meeting: meeting,
					content: store.content(of: meeting),
					busy: isProcessingThis,
					progress: controller.progress,
					status: controller.status,
					eta: controller.remaining,
					onRename: { newName in
						if let renamed = store.rename(meeting, to: newName) { selection = renamed.id }
					},
					onRegenerate: { count in controller.regenerate(meeting, speakerCount: count) },
					onCompress: { controller.compressAudio(meeting) },
					onDelete: { store.delete(meeting); selection = nil },
					onCancel: { controller.cancelProcessing() })
			} else if settings.meetingsDirURL == nil {
				// First run: guide the user to set up before anything else.
				ContentUnavailableView {
					Label("Welcome to AI Meeting Notes", systemImage: "waveform")
				} description: {
					Text("To get started, choose a folder where your meeting notes will be saved. Then pick a transcription model, and you're ready to record.")
				} actions: {
					SettingsLink { Text("Open Settings to set up") }
						.buttonStyle(.borderedProminent)
				}
			} else {
				ContentUnavailableView("No meeting selected", systemImage: "waveform",
					description: Text("Record a meeting, or pick one from the list."))
			}
		}
		.tint(brand)
		.onAppear { store.reload(folder: settings.meetingsDirURL) }
		.onChange(of: controller.activeID) {
			if let id = controller.activeID { selection = id }
		}
		.safeAreaInset(edge: .top, spacing: 0) { updateBanner }
	}

	/// A slim "update available" bar at the top of the window. Empty (no space)
	/// when the app is current or the user dismissed the notice.
	@ViewBuilder private var updateBanner: some View {
		if updates.updateAvailable, let v = updates.latestVersion {
			HStack(spacing: 10) {
				Image(systemName: "arrow.down.circle.fill").foregroundStyle(brand)
				Text("Version \(v) is available.").font(.callout)
				Spacer()
				if let url = updates.releaseURL {
					Link("Download", destination: url)
						.buttonStyle(.borderedProminent).controlSize(.small)
				}
				Button { updates.dismiss() } label: { Image(systemName: "xmark") }
					.buttonStyle(.borderless).controlSize(.small)
					.help("Dismiss until the next version")
			}
			.padding(.horizontal, 14).padding(.vertical, 8)
			.background(.bar)
		}
	}
}

struct MeetingRow: View {
	@EnvironmentObject var controller: RecordingController
	let meeting: Meeting
	private var isActive: Bool { controller.activeID == meeting.id }

	var body: some View {
		HStack(spacing: 10) {
			icon.font(.title2)
			VStack(alignment: .leading, spacing: 1) {
				Text(meeting.title).lineLimit(1)
				HStack(spacing: 5) {
					Text(meeting.modified, format: .dateTime.month().day().hour().minute())
					if meeting.durationSeconds > 0 { Text("· \(durationLabel(meeting.durationSeconds))") }
				}
				.font(.caption).foregroundStyle(.secondary)
			}
			Spacer(minLength: 0)
			if !isActive && noteIsOutdated(meeting.appVersion) {
				Image(systemName: "sparkles")
					.font(.caption).foregroundStyle(.orange)
					.help("Generated with an older version - re-generate to refresh")
			}
		}
		.padding(.vertical, 2)
	}

	@ViewBuilder private var icon: some View {
		if isActive && controller.isRecording {
			Image(systemName: "record.circle.fill").foregroundStyle(.red)
		} else if isActive && controller.busy {
			Image(systemName: "hourglass.circle.fill").foregroundStyle(.orange)
		} else {
			Image(systemName: "waveform.circle.fill").foregroundStyle(brand)
		}
	}
}

struct RecordPanel: View {
	@EnvironmentObject var controller: RecordingController
	@EnvironmentObject var settings: AppSettings
	@EnvironmentObject var detector: MeetingDetector

	/// Title of the meeting currently being processed (derived from its note path).
	private var activeTitle: String? {
		guard let id = controller.activeID else { return nil }
		return ((id as NSString).lastPathComponent as NSString).deletingPathExtension
	}

	var body: some View {
		VStack(alignment: .leading, spacing: 10) {
			if detector.suggestRecording && !controller.isRecording && !controller.busy {
				HStack(spacing: 8) {
					Image(systemName: "dot.radiowaves.left.and.right").foregroundStyle(brand)
					VStack(alignment: .leading, spacing: 1) {
						Text("Meeting detected").font(.caption.weight(.semibold))
						Text("Another app is using your mic.").font(.caption2).foregroundStyle(.secondary)
					}
					Spacer(minLength: 4)
					Button("Record") { detector.clear(); controller.start() }
						.controlSize(.small).buttonStyle(.borderedProminent)
					Button { detector.dismiss() } label: { Image(systemName: "xmark") }
						.controlSize(.small).buttonStyle(.borderless)
				}
				.padding(10)
				.background(RoundedRectangle(cornerRadius: 10).fill(brand.opacity(0.1)))
				.transition(.opacity)
			}
			// No notes folder yet: recording can't save anywhere, so make the fix
			// obvious instead of silently doing nothing when Record is clicked.
			if settings.meetingsDirURL == nil && !controller.isRecording && !controller.busy {
				HStack(spacing: 8) {
					Image(systemName: "exclamationmark.triangle.fill").foregroundStyle(.orange)
					VStack(alignment: .leading, spacing: 1) {
						Text("Choose a notes folder to start").font(.caption.weight(.semibold))
						Text("Meetings are saved as Markdown in a folder you pick.")
							.font(.caption2).foregroundStyle(.secondary)
					}
					Spacer(minLength: 4)
					SettingsLink { Text("Open Settings") }
						.controlSize(.small).buttonStyle(.borderedProminent)
				}
				.padding(10)
				.background(RoundedRectangle(cornerRadius: 10).fill(Color.orange.opacity(0.12)))
				.transition(.opacity)
			}

			HStack(spacing: 6) {
				Image(systemName: "globe").foregroundStyle(.secondary)
				Picker("Language", selection: $settings.language) {
					ForEach(meetingLanguages, id: \.code) { Text($0.name).tag($0.code) }
				}
				.labelsHidden()
			}
			.help("Pick the meeting's language for better accuracy")
			.disabled(controller.isRecording || controller.busy)

			if settings.speakerRecognitionEnabled {
				HStack(spacing: 6) {
					Image(systemName: "person.2").foregroundStyle(.secondary)
					Picker("Speakers", selection: $settings.speakerCount) {
						Text("Auto-detect").tag(0)
						ForEach(2...8, id: \.self) { Text("\($0) speakers").tag($0) }
					}
					.labelsHidden()
				}
				.help("How many people are on the other side of the call (improves speaker recognition)")
				.disabled(controller.isRecording || controller.busy)
			}

			Button(action: { controller.toggle() }) {
				Label(controller.isRecording ? "Stop & Transcribe" : "Record",
					systemImage: controller.isRecording ? "stop.fill" : "record.circle")
					.frame(maxWidth: .infinity)
			}
			.buttonStyle(.borderedProminent)
			.controlSize(.large)
			.tint(controller.isRecording ? .red : brand)
			.disabled(controller.busy || (settings.meetingsDirURL == nil && !controller.isRecording))
			.help(settings.meetingsDirURL == nil ? "Choose a notes folder in Settings first" : "")

			if controller.busy {
				if let title = activeTitle {
					Text(title)
						.font(.caption.weight(.semibold))
						.lineLimit(2).fixedSize(horizontal: false, vertical: true)
				}
				ProgressView(value: controller.progress).progressViewStyle(.linear)
				HStack {
					Text("\(Int(controller.progress * 100))%")
					if !controller.remaining.isEmpty {
						Spacer()
						Text(controller.remaining)
					}
					Spacer()
					Text(controller.elapsed)
				}
				.font(.caption).foregroundStyle(.secondary)
				Button("Stop processing", role: .destructive) { controller.cancelProcessing() }
					.controlSize(.small)
			} else {
				LevelBar(label: "System", level: controller.systemLevel)
				LevelBar(label: "Mic", level: controller.micLevel)
			}

			Text(controller.status)
				.font(.caption).foregroundStyle(.secondary)
				.lineLimit(3).fixedSize(horizontal: false, vertical: true)
		}
		.animation(.default, value: detector.suggestRecording)
		.onChange(of: controller.isRecording) {
			// Once recording, drop the nudge for this call so it doesn't reappear
			// after the recording stops while the meeting is still going.
			if controller.isRecording { detector.dismiss() }
		}
	}
}

struct LevelBar: View {
	let label: String
	let level: Float
	var body: some View {
		HStack(spacing: 8) {
			Text(label).font(.caption).foregroundStyle(.secondary).frame(width: 48, alignment: .leading)
			GeometryReader { geo in
				ZStack(alignment: .leading) {
					Capsule().fill(Color.secondary.opacity(0.15))
					Capsule().fill(brand.opacity(0.8))
						.frame(width: max(2, geo.size.width * CGFloat(min(max(level, 0), 1))))
				}
			}
			.frame(height: 6)
		}
	}
}

struct MeetingDetail: View {
	let meeting: Meeting
	let content: String
	let busy: Bool
	let progress: Double
	let status: String
	let eta: String
	let onRename: (String) -> Void
	let onRegenerate: (Int?) -> Void
	let onCompress: () -> Void
	let onDelete: () -> Void
	let onCancel: () -> Void
	@EnvironmentObject var settings: AppSettings

	/// True when this meeting still has uncompressed WAV tracks on disk.
	private var hasUncompressedAudio: Bool {
		guard let dir = settings.meetingsDirURL else { return false }
		let base = RecordingController.frontmatterValue("audio", in: content) ?? "recordings/\(meeting.title)"
		return ["mic.wav", "system.wav"].contains {
			FileManager.default.fileExists(atPath: dir.appendingPathComponent(base + "." + $0).path)
		}
	}
	@State private var titleField = ""
	@State private var confirmingDelete = false
	@State private var copied = false
	@State private var tab = 0
	/// Per-meeting remote-speaker count (experimental); seeded from the note.
	@State private var speakerCount = 0

	var body: some View {
		VStack(alignment: .leading, spacing: 0) {
			HStack(spacing: 8) {
				TextField("Title", text: $titleField)
					.textFieldStyle(.plain)
					.font(.title2.weight(.semibold))
					.onSubmit { onRename(titleField) }
				Spacer()
				Button {
					NSPasteboard.general.clearContents()
					NSPasteboard.general.setString(copyText(for: tab), forType: .string)
					copied = true
					DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { copied = false }
				} label: { Image(systemName: copied ? "checkmark" : "doc.on.doc") }
					.help(tab == 0 ? "Copy summary" : tab == 1 ? "Copy transcript" : "Copy full note as Markdown")
				Button { onRename(titleField) } label: { Image(systemName: "pencil") }
					.help("Rename")
					.disabled(titleField.trimmingCharacters(in: .whitespaces).isEmpty || titleField == meeting.title)
				Button { onRegenerate(settings.speakerRecognitionEnabled ? speakerCount : nil) } label: { Image(systemName: "arrow.clockwise") }
					.help("Re-transcribe & summarize")
					.disabled(busy)
				if hasUncompressedAudio {
					Button { onCompress() } label: { Image(systemName: "arrow.down.right.and.arrow.up.left") }
						.help("Compress audio to save space (no re-transcribing)")
						.disabled(busy)
				}
				Button(role: .destructive) { confirmingDelete = true } label: { Image(systemName: "trash") }
					.help("Delete meeting")
					.disabled(busy)
			}
			.padding(.horizontal, 20).padding(.top, 18).padding(.bottom, 10)
			.confirmationDialog("Delete “\(meeting.title)”?", isPresented: $confirmingDelete) {
				Button("Delete meeting & recording", role: .destructive, action: onDelete)
				Button("Cancel", role: .cancel) {}
			} message: {
				Text("This removes the note and its audio recordings. This can't be undone.")
			}

			if meeting.durationSeconds > 0 {
				Label("Duration \(durationLabel(meeting.durationSeconds))", systemImage: "clock")
					.font(.caption).foregroundStyle(.secondary)
					.padding(.horizontal, 20).padding(.bottom, 8)
			}

			if settings.speakerRecognitionEnabled && !busy {
				HStack(spacing: 6) {
					Image(systemName: "person.2").foregroundStyle(.secondary)
					Picker("Speakers", selection: $speakerCount) {
						Text("Auto-detect").tag(0)
						ForEach(2...8, id: \.self) { Text("\($0)").tag($0) }
					}
					.labelsHidden().fixedSize()
					Text("remote speakers · Re-generate to apply")
						.font(.caption).foregroundStyle(.secondary)
				}
				.font(.caption)
				.padding(.horizontal, 20).padding(.bottom, 8)
			}

			if noteIsOutdated(meeting.appVersion) && !busy {
				HStack(spacing: 10) {
					Image(systemName: "sparkles").foregroundStyle(.orange)
					VStack(alignment: .leading, spacing: 2) {
						Text("Generated with an older version" + (meeting.appVersion.isEmpty ? "" : " (\(meeting.appVersion))"))
							.font(.caption.weight(.semibold))
						Text("This app (\(appVersion)) improves the summary structure & quality. Re-generate to refresh this note.")
							.font(.caption).foregroundStyle(.secondary)
					}
					Spacer(minLength: 8)
					Button("Re-generate") { onRegenerate(settings.speakerRecognitionEnabled ? speakerCount : nil) }
						.controlSize(.small)
				}
				.padding(12)
				.background(RoundedRectangle(cornerRadius: 10).fill(Color.orange.opacity(0.12)))
				.padding(.horizontal, 20).padding(.bottom, 8)
			}

			if busy {
				HStack(spacing: 12) {
					VStack(alignment: .leading, spacing: 4) {
						ProgressView(value: progress).progressViewStyle(.linear)
						Text(eta.isEmpty ? status : "\(status)  ·  \(eta)")
							.font(.caption).foregroundStyle(.secondary)
					}
					Button("Stop", role: .destructive) { onCancel() }
						.controlSize(.small)
				}
				.padding(.horizontal, 20).padding(.bottom, 10)
			}

			Divider()

			TabView(selection: $tab) {
				ScrollView {
					NoteView(markdown: content, only: .summary)
						.frame(maxWidth: .infinity, alignment: .leading).padding(20)
				}
				.tabItem { Label("Summary", systemImage: "text.alignleft") }
				.tag(0)

				ScrollView {
					NoteView(markdown: content, only: .transcript)
						.frame(maxWidth: .infinity, alignment: .leading).padding(20)
				}
				.tabItem { Label("Transcript", systemImage: "waveform") }
				.tag(1)

				ScrollView {
					Text(content)
						.font(.system(.body, design: .monospaced))
						.textSelection(.enabled)
						.frame(maxWidth: .infinity, alignment: .leading).padding(20)
				}
				.tabItem { Label("Markdown", systemImage: "curlybraces") }
				.tag(2)
			}
			.padding(8)
		}
		.onAppear { titleField = meeting.title; speakerCount = meeting.speakerCount }
		.onChange(of: meeting.id) { titleField = meeting.title; speakerCount = meeting.speakerCount }
	}

	/// Markdown to copy for the active tab: summary, transcript, or the full note.
	private func copyText(for tab: Int) -> String {
		switch tab {
		case 0: return Self.summaryMarkdown(content)
		case 1: return Self.transcriptMarkdown(content)
		default: return content
		}
	}

	private static func stripFrontmatter(_ content: String) -> String {
		guard content.hasPrefix("---"),
			let end = content.range(of: "\n---", range: content.index(content.startIndex, offsetBy: 3)..<content.endIndex)
		else { return content }
		return String(content[end.upperBound...])
	}

	/// Title + summary sections (everything before the Transcript), no frontmatter.
	private static func summaryMarkdown(_ content: String) -> String {
		var s = stripFrontmatter(content)
		if let r = s.range(of: "\n## Transcript") { s = String(s[..<r.lowerBound]) }
		return s.trimmingCharacters(in: .whitespacesAndNewlines)
	}

	/// Just the Transcript section body (between `## Transcript` and `## Audio`).
	private static func transcriptMarkdown(_ content: String) -> String {
		let s = stripFrontmatter(content)
		guard let start = s.range(of: "## Transcript") else { return "" }
		var t = String(s[start.upperBound...])
		if let audio = t.range(of: "\n## Audio") { t = String(t[..<audio.lowerBound]) }
		return t.trimmingCharacters(in: .whitespacesAndNewlines)
	}
}

/// Renders a meeting note's markdown as styled sections (Summary, Action items
/// as checkboxes, Transcript with speaker labels).
struct NoteView: View {
	enum Filter { case all, summary, transcript }
	let markdown: String
	var only: Filter = .all

	private var visibleSections: [Section] {
		sections().filter { sec in
			// The Audio section is `![[…]]` embeds for Obsidian; the app hides it.
			if sec.title.lowercased() == "audio" { return false }
			switch only {
			case .all: return true
			case .summary: return sec.title.lowercased() != "transcript"
			case .transcript: return sec.title.lowercased() == "transcript"
			}
		}
	}

	var body: some View {
		VStack(alignment: .leading, spacing: 18) {
			ForEach(Array(visibleSections.enumerated()), id: \.offset) { _, sec in
				let isCard = sec.title.lowercased() != "transcript"
				VStack(alignment: .leading, spacing: 10) {
					Label(sec.title, systemImage: icon(for: sec.title))
						.font(.headline)
						.foregroundStyle(brand)
					body(for: sec)
				}
				.padding(isCard ? 16 : 0)
				.frame(maxWidth: .infinity, alignment: .leading)
				.background {
					if isCard { RoundedRectangle(cornerRadius: 12).fill(Color.secondary.opacity(0.07)) }
				}
			}
		}
		.frame(maxWidth: 780, alignment: .leading)
		.textSelection(.enabled)
	}

	private struct Section { let title: String; let lines: [String] }

	private func icon(for title: String) -> String {
		switch title.lowercased() {
		case "short summary": return "text.quote"
		case "summary": return "text.alignleft"
		case "topics discussed", "topics", "discussion": return "bubble.left.and.bubble.right"
		case "action items": return "checklist"
		case "transcript": return "waveform"
		default: return "doc.text"
		}
	}

	@ViewBuilder
	private func body(for sec: Section) -> some View {
		let title = sec.title.lowercased()
		if title == "action items" {
			VStack(alignment: .leading, spacing: 6) {
				ForEach(Array(sec.lines.enumerated()), id: \.offset) { _, line in actionItem(line) }
			}
		} else if title == "transcript" {
			let lines = sec.lines.filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
			VStack(alignment: .leading, spacing: 8) {
				ForEach(Array(lines.enumerated()), id: \.offset) { _, line in transcriptLine(line) }
			}
		} else if title == "topics discussed" || title == "topics" || title == "discussion" {
			topicBlocks(sec.lines)
		} else {
			richText(sec.lines)
		}
	}

	/// Each `### topic` becomes its own prominent block (numbered heading +
	/// accent bar + its paragraphs/bullets), so topics stand apart from the
	/// summary prose.
	@ViewBuilder
	private func topicBlocks(_ lines: [String]) -> some View {
		let blocks = groupTopics(lines)
		VStack(alignment: .leading, spacing: 12) {
			ForEach(Array(blocks.enumerated()), id: \.offset) { i, block in
				HStack(alignment: .top, spacing: 12) {
					RoundedRectangle(cornerRadius: 3).fill(brand).frame(width: 4)
					VStack(alignment: .leading, spacing: 8) {
						if !block.title.isEmpty {
							HStack(alignment: .firstTextBaseline, spacing: 8) {
								Text("\(i + 1)")
									.font(.caption.weight(.bold))
									.foregroundStyle(.white)
									.frame(width: 22, height: 22)
									.background(Circle().fill(brand))
								Text(block.title)
									.font(.title3.weight(.semibold))
									.foregroundStyle(.primary)
							}
						}
						richText(block.lines)
							.font(.body)
					}
				}
				.padding(14)
				.frame(maxWidth: .infinity, alignment: .leading)
				.background(RoundedRectangle(cornerRadius: 10).fill(brand.opacity(0.06)))
			}
		}
	}

	private func groupTopics(_ lines: [String]) -> [(title: String, lines: [String])] {
		var result: [(String, [String])] = []
		for raw in lines {
			let line = raw.trimmingCharacters(in: .whitespaces)
			if line.hasPrefix("### ") {
				result.append((String(line.dropFirst(4)), []))
			} else if !line.isEmpty {
				if result.isEmpty { result.append(("", [])) }
				result[result.count - 1].1.append(raw)
			}
		}
		return result
	}

	/// Renders paragraphs, `#`-headings, `- `/`* ` bullets, and `1.` numbered lists.
	@ViewBuilder
	private func richText(_ lines: [String]) -> some View {
		VStack(alignment: .leading, spacing: 6) {
			ForEach(Array(lines.enumerated()), id: \.offset) { _, raw in
				let line = raw.trimmingCharacters(in: .whitespaces)
				if let heading = headingText(line) {
					Text(heading)
						.font(.subheadline.weight(.semibold))
						.padding(.top, 4)
				} else if line.hasPrefix("- ") || line.hasPrefix("* ") {
					HStack(alignment: .firstTextBaseline, spacing: 8) {
						Text("•").foregroundStyle(.secondary)
						inline(String(line.dropFirst(2)))
					}
				} else if let (num, rest) = numberedItem(line) {
					HStack(alignment: .firstTextBaseline, spacing: 8) {
						Text(num).foregroundStyle(.secondary).monospacedDigit()
						inline(rest)
					}
				} else if !line.isEmpty {
					inline(line)
				}
			}
		}
	}

	/// Strip a leading run of `#` (a Markdown heading) and return the text, or nil.
	private func headingText(_ line: String) -> String? {
		guard line.hasPrefix("#") else { return nil }
		let hashes = line.prefix(while: { $0 == "#" })
		let after = line.dropFirst(hashes.count)
		guard after.hasPrefix(" ") else { return nil }
		return String(after).trimmingCharacters(in: .whitespaces)
	}

	/// Parse a `1. text` / `1) text` numbered-list item into (number, text).
	private func numberedItem(_ line: String) -> (String, String)? {
		let digits = line.prefix(while: { $0.isNumber })
		guard !digits.isEmpty else { return nil }
		let after = line.dropFirst(digits.count)
		guard after.hasPrefix(". ") || after.hasPrefix(") ") else { return nil }
		return ("\(digits).", String(after.dropFirst(2)))
	}

	@ViewBuilder
	private func actionItem(_ line: String) -> some View {
		let t = line.trimmingCharacters(in: .whitespaces)
		if t.hasPrefix("- [ ]") || t.hasPrefix("- [x]") || t.hasPrefix("- [X]") {
			let checked = t.hasPrefix("- [x]") || t.hasPrefix("- [X]")
			HStack(alignment: .firstTextBaseline, spacing: 8) {
				Image(systemName: checked ? "checkmark.circle.fill" : "circle")
					.foregroundStyle(checked ? .green : .secondary)
				inline(String(t.dropFirst(5)).trimmingCharacters(in: .whitespaces))
			}
		} else if t.hasPrefix("- ") {
			HStack(alignment: .firstTextBaseline, spacing: 8) {
				Text("•").foregroundStyle(.secondary)
				inline(String(t.dropFirst(2)))
			}
		} else {
			inline(t)
		}
	}

	@ViewBuilder
	private func transcriptLine(_ line: String) -> some View {
		let (time, afterTime) = splitTimestamp(line)
		if let (speaker, rest) = speakerSplit(afterTime) {
			HStack(alignment: .top, spacing: 10) {
				VStack(alignment: .leading, spacing: 2) {
					Text(speaker)
						.font(.caption2.weight(.semibold))
						.foregroundStyle(.white)
						.padding(.horizontal, 7).padding(.vertical, 2)
						.background(speaker == "You" ? brand : Color.gray, in: Capsule())
					if let time { Text(time).font(.caption2).monospacedDigit().foregroundStyle(.secondary) }
				}
				.frame(width: 54, alignment: .leading)
				inline(rest).frame(maxWidth: .infinity, alignment: .leading)
			}
		} else {
			// Continuation paragraph of the same speaker: timestamp gutter + text.
			HStack(alignment: .top, spacing: 10) {
				Text(time ?? "")
					.font(.caption2).monospacedDigit().foregroundStyle(.secondary)
					.frame(width: 54, alignment: .leading)
				inline(afterTime).frame(maxWidth: .infinity, alignment: .leading)
			}
		}
	}

	private func speakerSplit(_ line: String) -> (String, String)? {
		for s in ["You", "Them"] {
			let p = "**\(s):**"
			if line.hasPrefix(p) { return (s, String(line.dropFirst(p.count)).trimmingCharacters(in: .whitespaces)) }
		}
		return nil
	}

	/// Pull a leading `[m:ss]` / `[h:mm:ss]` timestamp off a transcript line.
	private func splitTimestamp(_ line: String) -> (String?, String) {
		guard line.hasPrefix("["), let close = line.firstIndex(of: "]") else { return (nil, line) }
		let ts = String(line[line.index(after: line.startIndex)..<close])
		guard ts.contains(":"), ts.allSatisfy({ $0.isNumber || $0 == ":" }) else { return (nil, line) }
		let rest = String(line[line.index(after: close)...]).trimmingCharacters(in: .whitespaces)
		return (ts, rest)
	}

	private func inline(_ s: String) -> Text {
		if let a = try? AttributedString(markdown: s, options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)) {
			return Text(a)
		}
		return Text(s)
	}

	/// Strip frontmatter + the H1, then split into `## ` sections.
	private func sections() -> [Section] {
		var text = markdown
		if text.hasPrefix("---"), let end = text.range(of: "\n---", range: text.index(text.startIndex, offsetBy: 3)..<text.endIndex) {
			text = String(text[end.upperBound...])
		}
		var result: [Section] = []
		var current: String?
		var buffer: [String] = []
		var preamble: [String] = []
		func trimEdges(_ lines: [String]) -> [String] {
			Array(lines.drop(while: { $0.isEmpty }).reversed().drop(while: { $0.isEmpty }).reversed())
		}
		func flush() {
			if let c = current {
				result.append(Section(title: c, lines: trimEdges(buffer)))
			}
			buffer = []
		}
		for raw in text.components(separatedBy: "\n") {
			if raw.hasPrefix("## ") { flush(); current = String(raw.dropFirst(3)).trimmingCharacters(in: .whitespaces) }
			else if raw.hasPrefix("# ") { continue }
			else if current != nil { buffer.append(raw) }
			else { preamble.append(raw) } // content before the first "## " heading
		}
		flush()
		// Some models emit the summary as plain text with no "## " headings; that
		// content lands in `preamble` and would otherwise be invisible in the
		// Summary tab. Surface it as a Summary section (only when there isn't a
		// real summary section already).
		let lead = trimEdges(preamble)
		// "transcript" and "audio" aren't summary content, so if those are the only
		// real sections, treat the preamble as the summary.
		let hasSummarySection = result.contains {
			let t = $0.title.lowercased()
			return t != "transcript" && t != "audio"
		}
		if !lead.isEmpty, !hasSummarySection {
			result.insert(Section(title: "Summary", lines: lead), at: 0)
		}
		return result
	}
}